### ISSUE TITLE
YodaQA not generating answers

### ISSUE THREAD

**Issue by bhanuprakashganta** [brmson/yodaqa#52]
I am getting the below error while submitting query to YodaQA.
Please help.

*************************ERROR LOG***********************************
INFO WebInterface - 127.0.0.1 :: new question 1328124633 <<Who wrote Ender's Game?>>
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from [jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-sentence-en-maxent/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-sentence-en-maxent-20120616.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/sentence-en-maxent.bin] redirected from [jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent-20120616.1.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/sentence-en-maxent.properties]
INFO ResourceObjectProviderBase - Producing resource took 70ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from [jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-token-en-maxent/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-token-en-maxent-20120616.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/token-en-maxent.bin] redirected from [jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent-20120616.1.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/token-en-maxent.properties]
INFO ResourceObjectProviderBase - Producing resource took 181ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from [jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-upstream-parser-en-rnn/jars/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-upstream-parser-en-rnn-20140104.jar!/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/lib/parser-en-rnn.ser.gz] redirected from [jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn/jars/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn-20140104.1.jar!/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/lib/parser-en-rnn.properties]
Jun 23, 2016 12:08:01 PM de.tudarmstadt.ukp.dkpro.core.stanfordnlp.StanfordParser$StanfordParserModelProvider produceResource(511)
INFO: Loading parser from serialized file jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-upstream-parser-en-rnn/jars/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-upstream-parser-en-rnn-20140104.jar!/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/lib/parser-en-rnn.ser.gz ...
INFO ResourceObjectProviderBase - Producing resource took 2041ms
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl/1.7.0/660e6a99e1d68595970d004988310949685ff957/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.7.0.jar!/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/en-ptb-pos.map
INFO ResourceObjectProviderBase - Producing resource took 0ms
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.api.syntax-asl/1.7.0/5c91e9a53843bf951188e6f3c4fe67986bbf5a6e/de.tudarmstadt.ukp.dkpro.core.api.syntax-asl-1.7.0.jar!/de/tudarmstadt/ukp/dkpro/core/api/syntax/tagset/en-ptb-constituency.map
INFO ResourceObjectProviderBase - Producing resource took 1ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-date/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-date-20100907.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/ner-en-date.bin
INFO ResourceObjectProviderBase - Producing resource took 705ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-location/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-location-20100907.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/ner-en-location.bin
INFO ResourceObjectProviderBase - Producing resource took 615ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-money/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-money-20100907.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/ner-en-money.bin
INFO ResourceObjectProviderBase - Producing resource took 565ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-organization/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-organization-20100907.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/ner-en-organization.bin
INFO ResourceObjectProviderBase - Producing resource took 586ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-percentage/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-percentage-20100907.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/ner-en-percentage.bin
INFO ResourceObjectProviderBase - Producing resource took 585ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-person/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-person-20130624.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/ner-en-person.bin
INFO ResourceObjectProviderBase - Producing resource took 1156ms
INFO ResourceObjectProviderBase - :: loading settings :: url = jar:file:/home/ec2-user/.gradle/caches/modules-2/files-2.1/org.apache.ivy/ivy/2.3.0/c5ebf1c253ad4959a29f4acfe696ee48cdd9f473/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
INFO ResourceObjectProviderBase - Producing resource from jar:file:/home/ec2-user/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-time/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-ner-en-time-20100907.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/ner-en-time.bin
INFO ResourceObjectProviderBase - Producing resource took 571ms
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at cz.brmlab.yodaqa.provider.rdf.DBpediaTitles.queryFuzzyLookup(DBpediaTitles.java:256)
        at cz.brmlab.yodaqa.provider.rdf.DBpediaTitles.query(DBpediaTitles.java:102)
        at cz.brmlab.yodaqa.analysis.question.CluesToConcepts.process(CluesToConcepts.java:104)
        at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:309)
        at cz.brmlab.yodaqa.flow.asb.MultiprocessingAnalysisEngine_MultiplierOk.processAndOutputNewCASes(MultiprocessingAnalysisEngine_MultiplierOk.java:218)
        at cz.brmlab.yodaqa.flow.asb.MultiThreadASB$AggregateCasIterator$1.call(MultiThreadASB.java:772)
        at cz.brmlab.yodaqa.flow.asb.MultiThreadASB$AggregateCasIterator$1.call(MultiThreadASB.java:754)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
*** http://dbp-labels.ailao.eu:5000 or http://dbp-labels.ailao.eu:5001 label lookup query (temporarily?) failed, retrying in a moment...
*  http://dbp-labels.ailao.eu:5000java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at cz.brmlab.yodaqa.provider.rdf.DBpediaTitles.queryFuzzyLookup(DBpediaTitles.java:256)
        at cz.brmlab.yodaqa.provider.rdf.DBpediaTitles.query(DBpediaTitles.java:102)
        at cz.brmlab.yodaqa.analysis.question.CluesToConcepts.process(CluesToConcepts.java:104)
        at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:309)
        at cz.brmlab.yodaqa.flow.asb.MultiprocessingAnalysisEngine_MultiplierOk.processAndOutputNewCASes(MultiprocessingAnalysisEngine_MultiplierOk.java:218)
        at cz.brmlab.yodaqa.flow.asb.MultiThreadASB$AggregateCasIterator$1.call(MultiThreadASB.java:772)
        at cz.brmlab.yodaqa.flow.asb.MultiThreadASB$AggregateCasIterator$1.call(MultiThreadASB.java:754)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
*** http://dbp-labels.ailao.eu:5000 or http://dbp-labels.ailao.eu:5001 label lookup query (temporarily?) failed, retrying in a moment...
ALERT: main seems stuck for more than 300s waiting for a job delivery.
Thread[main,5,main]  - Future java.util.concurrent.FutureTask@2e95d163 done false canc false :: AE cz.brmlab.yodaqa.analysis.question.QuestionAnalysisAE from CAS org.apache.uima.cas.impl.CASImpl@6d67667f (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@109d3527)

ALERT: pool-2-thread-1 seems stuck for more than 300s waiting for a job delivery.
Thread[pool-2-thread-1,5,main]  - Future java.util.concurrent.FutureTask@773ffaa3 done false canc false :: AE cz.brmlab.yodaqa.analysis.question.CluesToConcepts from CAS org.apache.uima.cas.impl.CASImpl@6d67667f (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@210fed76)

**Comment by pasky** [comment]
Hi! The connectivity to dbp-labels seems fine to me.  Maybe your IPv6
connectivity is somehow broken?

**Comment by bhanuprakashganta** [comment]
1)      My YodaQA instance is running on AWS. Does it mean that we need to enable IPV6 in the VM to talk to dbp-labels (http://dbp-labels.ailao.eu:5000, http://dbp-labels.ailao.eu:5001)?
2)      I am not able to see the any response to PING for the dbp-servers (http://dbp-labels.ailao.eu:5000, http://dbp-labels.ailao.eu:5001)
 
Am I missing something here?

**Comment by pasky** [comment]
Sorry but I just cannot reproduce that issue, pinging
dbp-labels.ailao.eu from aws works fine.  If you can't ping, that indeed
is connected to your issue, but please examine your local network setup.

**Comment by k0105** [comment]
Erm... Can't ping http://dbp-labels.ailao.eu:5000 sounds suspicious to me. You shouldn't add http while pinging and since ping happens on ICMP you can't ping ports, so in case you tried something like `ping http://dbp-labels.ailao.eu:5000` that's bound to fail, whereas `ping dbp-labels.ailao.eu` should work. I can confirm that the servers are also fine when calling in from the US. Similarly, note that trying to access the above URLs via HTTP is bound to fail as well, but something like `http://dbp-labels.ailao.eu:5001/search/Nietzsche` should work just fine.

**Comment by bhanuprakashganta** [comment]
OK. Checked the current network policy and found that the issue was with outbound ports being blocked in the AWS. After these ports were enabled, I am able to access these URL's. YodaQA web is able to access the url's.
